import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head'
import NavBar from '@/components/NavBar'
import Loader from '@/components/Loader';
import Presentation from '@/components/Presentation';
import AboutMe from '@/components/AboutMe';
import Projects from '@/components/Projects';
import Skills from '@/components/Skills';
import Contact from '@/components/Contact';
import LanguageSelector from '@/components/LangSelector/LangSelector';
import UseContextProvider from '@/components/context/Context';

export default function Home() {
  const { asPath } = useRouter();


  useEffect(() => {
    console.error = () => { }; console.warn = () => { }; setTimeout(() => { console.clear(); }, 700);
    if (typeof window !== "undefined" && asPath == '/') {
      const body = document.getElementsByTagName('body')[0];
      body.style.background = "linear-gradient(to bottom, rgb(32, 32, 32), rgb(32, 32, 32))";

      window.addEventListener('load', () => {
        body.style.background = "linear-gradient(to bottom, rgb(32, 32, 32), rgb(32, 32, 32))";
      });
    }
  }, []);

  return (
    <>

      <Head>
        <title>Portfolio - Alex Zorzin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Loader />
      <canvas className="orb-canvas"></canvas>
      
      
      <UseContextProvider>
      <LanguageSelector/>
      <NavBar />
      <Presentation />
      <AboutMe />
      <Projects />
      <Skills />
      <Contact />
      </UseContextProvider>
      <script type="module" src="./js/Bg-gradient.js"></script>
    </>
  )
}
